--What is the most common room type in NYC Airbnb listings?--

SELECT room_type, COUNT(room_type) AS num_rooms
FROM room_types
GROUP BY room_type
ORDER BY num_rooms DESC;

--What is the average price of a listing by room type?--

SELECT  room_type, ROUND(AVG(price),2) AS avg_price
FROM room_types 
JOIN prices 
USING(listing_id)
GROUP BY room_type 
ORDER BY avg_price DESC;  

--Which borough has the highest average price per month?--

SELECT borough, AVG(price_per_month) AS avg_price_per_month
FROM prices
GROUP BY borough
ORDER BY avg_price_per_month DESC;

--How many listings of each room type are in each borough?--

SELECT borough, room_type, COUNT(room_type) AS num_listing
FROM room_types
JOIN prices
USING(listing_id)
GROUP BY borough, room_type;

--How many listings in each room type category have a price of over $500 per night?--

SELECT room_type, COUNT(room_type) AS listings
FROM room_types
JOIN prices
USING(listing_id)
WHERE price > 500
GROUP BY room_type;

--What is the distribution of listing prices by neighborhood?--
SELECT neighbourhood, MIN(price) AS min_price, MAX(price) AS max_price, AVG(price) AS avg_price
FROM prices
GROUP BY neighbourhood
ORDER BY avg_price DESC;

--What is the estimated amount of revenue generated by hosts in each borough?--

SELECT borough, SUM(price * booked_days_365) AS revenue
FROM reviews
JOIN prices
USING(listing_id)
GROUP BY borough;

--What is the average price per month for listings in each neighborhood?--

SELECT neighbourhood, room_type, AVG(price_per_month) AS avg_price_per_month
FROM prices
JOIN room_types
USING(listing_id)
GROUP BY neighbourhood, room_type
ORDER BY room_type, avg_price_per_month DESC;

--How many listings have no reviews?--

SELECT COUNT(room_type)
FROM room_types
JOIN reviews
USING(listing_id)
WHERE number_of_reviews is NULL;

--How do the estimated book days correlate with the price of an Airbnb listing in New York City?--

SELECT CORR(price, booked_days_365) AS correlation
FROM prices
JOIN reviews
USING(listing_id);


--Bonus Questions:

/* What is the average price per room type for listings that have at least 100 reviews and are available more 
than 200 days a year?*/

SELECT room_type, AVG(price) AS avg_price
FROM prices
JOIN room_types AS r
USING(listing_id)
WHERE r.listing_id IN
    (SELECT listing_id
    FROM reviews
    WHERE number_of_reviews >= 100 AND availability_365 >200)
GROUP BY room_type;

--How many hosts have more than one listing, and what's the maximum number of listings by a single host name?--

SELECT COUNT(host_name) AS num_host,
    (SELECT max(calculated_host_listings_count)
    FROM reviews) AS max_count
FROM reviews
WHERE calculated_host_listings_count >1;

/* Determine the top 5 hosts who have the highest price_per_month for their listings, considering only hosts 
who have at least 10 listings. */

SELECT host_name, AVG(price_per_month) AS avg_price_per_month
FROM reviews
JOIN prices
USING(listing_id)
WHERE calculated_host_listings_count >=10
GROUP BY host_name
ORDER BY avg_price_per_month DESC
LIMIT 5;

/*Calculate the average price_per_month for each neighbourhood, taking into account only listings where the 
host has a minimum_nights value that is higher than the average minimum_nights value across all listings.*/

SELECT neighbourhood, AVG(price_per_month) AS avg_price_per_month
FROM prices
JOIN reviews
USING(listing_id)
WHERE minimum_nights > (SELECT avg(minimum_nights)
                        FROM reviews)
GROUP BY neighbourhood;
